### ISSUE TITLE
Question about motivation

### ISSUE THREAD

**Issue by redthor** [alexsasharegan/dotenv#2]
Hi there,
I'm just interested in your motivation. You've said:
> (inspired by: https://github.com/joho/godotenv).
so I'm wondering how this package differs.
Thanks

**Comment by alexsasharegan** [comment]
The issue title seems a bit confusing. This is a personal project--possibly my first go package. I haven't touched in almost 2 years. Peek inside, run it against tests if you want, but use something else for production work.
